apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-10di
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-10di
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-10di
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-10di
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-10di
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xnya-tenant/status-quarkus-io/statusquarkusio-10di@sha256:35f2c9e5e400e12fdb3094c9829394b80996c6d9c0fe4ffb6095e0fe5d653943
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
